### ISSUE TITLE
`make test-e2e` fails with error

### ISSUE THREAD

**Issue by DhritiShikhar** [openshift/external-dns-operator#135]
```
➜  external-dns-operator git:(main) make test-e2e
go test \
-ldflags "-X github.com/openshift/external-dns-operator/pkg/version.SHORTCOMMIT=ea98598 -X github.com/openshift/external-dns-operator/pkg/version.COMMIT=ea9859875676474644424ecf3ec7c0ce52836577" \
-timeout 1h \
-count 1 \
-v \
-tags e2e \
-run "" \
./test/e2e
I0421 10:46:33.230220  653910 request.go:665] Waited for 1.049125091s due to client-side throttling, not priority and fairness, request: GET:https://api.ci-ln-gis99cb-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443/apis/batch/v1?timeout=32s
panic: environment variable DNS_PROVIDER must be set

goroutine 1 [running]:
github.com/openshift/external-dns-operator/test/e2e.mustGetEnv({0x196e768, 0xc})
	/home/dhritishikhar/go/src/github.com/openshift/external-dns-operator/test/e2e/util.go:120 +0x8e
github.com/openshift/external-dns-operator/test/e2e.TestMain(0x442691?)
	/home/dhritishikhar/go/src/github.com/openshift/external-dns-operator/test/e2e/operator_test.go:133 +0x174
main.main()
	_testmain.go:55 +0x1d3
FAIL	github.com/openshift/external-dns-operator/test/e2e	3.859s
FAIL
make: *** [Makefile:115: test-e2e] Error 1
➜  external-dns-operator git:(main) 

```

**Comment by DhritiShikhar** [comment]
Closing this. README has the information -> https://github.com/openshift/external-dns-operator#running-end-to-end-tests-manually
